##
## EPITECH PROJECT, 2021
## lib
## File description:
## Makefile
##

all:
	$(MAKE) -C my

clean:
	$(MAKE) -C my clean

fclean:
	$(MAKE) -C my fclean

re:
	$(MAKE) -C my re

.PHONY:	all clean fclean re

